-- Seed all 66 books of the Bible in canonical order
-- Old Testament (39 books): Genesis through Malachi
-- New Testament (27 books): Matthew through Revelation

INSERT INTO books (name, testament, book_order) VALUES
  ('Genesis', 'old', 1),
  ('Exodus', 'old', 2),
  ('Leviticus', 'old', 3),
  ('Numbers', 'old', 4),
  ('Deuteronomy', 'old', 5),
  ('Joshua', 'old', 6),
  ('Judges', 'old', 7),
  ('Ruth', 'old', 8),
  ('1 Samuel', 'old', 9),
  ('2 Samuel', 'old', 10),
  ('1 Kings', 'old', 11),
  ('2 Kings', 'old', 12),
  ('1 Chronicles', 'old', 13),
  ('2 Chronicles', 'old', 14),
  ('Ezra', 'old', 15),
  ('Nehemiah', 'old', 16),
  ('Esther', 'old', 17),
  ('Job', 'old', 18),
  ('Psalms', 'old', 19),
  ('Proverbs', 'old', 20),
  ('Ecclesiastes', 'old', 21),
  ('Song of Solomon', 'old', 22),
  ('Isaiah', 'old', 23),
  ('Jeremiah', 'old', 24),
  ('Lamentations', 'old', 25),
  ('Ezekiel', 'old', 26),
  ('Daniel', 'old', 27),
  ('Hosea', 'old', 28),
  ('Joel', 'old', 29),
  ('Amos', 'old', 30),
  ('Obadiah', 'old', 31),
  ('Jonah', 'old', 32),
  ('Micah', 'old', 33),
  ('Nahum', 'old', 34),
  ('Habakkuk', 'old', 35),
  ('Zephaniah', 'old', 36),
  ('Haggai', 'old', 37),
  ('Zechariah', 'old', 38),
  ('Malachi', 'old', 39),
  ('Matthew', 'new', 40),
  ('Mark', 'new', 41),
  ('Luke', 'new', 42),
  ('John', 'new', 43),
  ('Acts', 'new', 44),
  ('Romans', 'new', 45),
  ('1 Corinthians', 'new', 46),
  ('2 Corinthians', 'new', 47),
  ('Galatians', 'new', 48),
  ('Ephesians', 'new', 49),
  ('Philippians', 'new', 50),
  ('Colossians', 'new', 51),
  ('1 Thessalonians', 'new', 52),
  ('2 Thessalonians', 'new', 53),
  ('1 Timothy', 'new', 54),
  ('2 Timothy', 'new', 55),
  ('Titus', 'new', 56),
  ('Philemon', 'new', 57),
  ('Hebrews', 'new', 58),
  ('James', 'new', 59),
  ('1 Peter', 'new', 60),
  ('2 Peter', 'new', 61),
  ('1 John', 'new', 62),
  ('2 John', 'new', 63),
  ('3 John', 'new', 64),
  ('Jude', 'new', 65),
  ('Revelation', 'new', 66);